### Start with importing class

In [26]:
from desummation import Desummation
import numpy as np
dsm = Desummation()

### Create new matrix
$$
    A = \begin{pmatrix}
    3 & 7 & 2 & 0 \\
    -4 & 2 & 0 & -3 \\
    5 & 0 & 2 & -1 \\
    5 & -5 & -2 & -4 \\
    \end{pmatrix} 
$$

In [27]:
A = [[3, 7, 2, 0], [-4, 2, 0, -3], [5, 0, 2, -1], [5, -5, -2, -4]] 

### Now fit some random matrices to this matrix

In [28]:
dsm.fit(A, 8)

### Get all the information you might need

In [29]:
dsm.basis.matrices[3]

array([[-0.7098396 ,  0.47015769,  1.21240082,  0.59766042],
       [ 0.46663857, -0.1312178 , -0.37645973,  0.70721657],
       [-0.98577392, -1.48245017,  2.01419301, -1.31020514],
       [ 0.03554717,  0.03243757, -0.548848  ,  0.95764423]])

In [30]:
dsm.optimizer.weights

[-0.3109799431976894,
 -0.5499703758282672,
 -1.7964019674141696,
 -0.6785899785077358,
 -0.5939155007919901,
 -0.6142138910122155,
 -1.3479122316141288,
 -1.2321574177735348]

### Now let's see which matrix we got

In [31]:
dsm.predict(A)

array([[ 1.34990384,  0.95643207,  0.43561249, -0.02665136],
       [-0.29236347,  0.78428379, -2.2888742 , -2.93923199],
       [ 3.84723599, -1.35431891, -0.88175581, -0.03974287],
       [-0.32984198,  3.01127932,  1.70332905, -7.34261111]])

In [32]:
np.array(A)

array([[ 3,  7,  2,  0],
       [-4,  2,  0, -3],
       [ 5,  0,  2, -1],
       [ 5, -5, -2, -4]])

In [33]:
dsm.optimizer.errors[-1]

20.869407842407995

### This is not very good approximation.
#### Certain ways to improve this:
- ##### make more trials for weights searching
- ##### make more random matrices
- ##### change metric between matrices
- ##### change distribution of elements in matrices

In [73]:
dsm.fit(A, 16, n_trials=2000, distribution='exponential', scale=1)

In [74]:
dsm.predict(A)

array([[ 2.87421501,  6.79717319,  1.52766636, -0.22118675],
       [-3.72658609,  2.03040845, -0.14152504, -3.42589764],
       [ 5.51630597,  0.34007234,  1.85824988, -1.18088964],
       [ 5.34983387, -4.25195159, -2.25179391, -4.2147999 ]])

In [40]:
np.array(A)

array([[ 3,  7,  2,  0],
       [-4,  2,  0, -3],
       [ 5,  0,  2, -1],
       [ 5, -5, -2, -4]])

In [75]:
dsm.optimizer.errors[-1]

1.4933985861243124